Referensi untuk CONTIBUTING.md
PythonID/PythonID.github.io pull request #11
Opened 2020-08-26 12:46 UTC by dvrg

Mungkin seperti ini yang sy maksud pak @irvansemestanya

2020-08-26 12:55 UTC, irvansemestanya commented
Link2nya nggak diisi?

2020-08-26 12:58 UTC, irvansemestanya commented on CONTRIBUTING.md
> +```markdown
Ini kayaknya aneh ya, cuma buka format doang? Bawahnya langsung bagian berikutnya....?

2020-08-26 13:03 UTC, dvrg commented on CONTRIBUTING.md
> +```markdown
Iya pak, format dengan penjelasan. Apa perlu dikasih contoh nya ?

2020-08-26 13:19 UTC, irvansemestanya commented on CONTRIBUTING.md
> +```markdown
Saya biasanya ngelink ke https://guides.github.com/features/mastering-markdown/

Bebas sih mau dikasih contoh di dalam sini atau bagaimana. Yang penting jangan salah buka tutup markdownnya saja :D

2020-08-26 13:20 UTC, irvansemestanya commented
Tinggal putuskan benerin buka tutup markdownnya atau bagaimana

2020-08-26 14:25 UTC, dvrg commented
Karena itu template markdown yang bakalan di gunakan di issue, oleh karenanya hasil tampilan harus markdown pak, jadi si pembuat issue tinggal copas dan ganti kata2 nya saja si. maksud saya begitu :smile:

2020-08-26 14:29 UTC, irvansemestanya commented
Oh, kalau begitu, tolong dibuat kata-katanya jadi seperti... "Repo ini tidak ada template issue, jadi silakan bebas buat issue-nya berisi apa."

Saya sih lagi malas mikir. Kalau ada usul mau template bagaimana, silakan 😂

2020-08-26 15:20 UTC, dvrg commented on CONTRIBUTING.md
> +```
Sudah saya hilangkan opening markdown format code nya pak. Dan Ini referensi untuk format template nya.

2020-08-26 15:22 UTC, irvansemestanya requested changes

2020-08-26 15:22 UTC, irvansemestanya commented on CONTRIBUTING.md
> +```
Oh! Ooooooooh! Maaf saya baru paham sekarang. Sudah benar pakai markdown tadi berarti 😅

2020-08-26 15:23 UTC, dvrg commented on CONTRIBUTING.md
> +```markdown
sudah saya perbaiki di  [7a88173](https://github.com/PythonID/PythonID.github.io/pull/11/commits/7a881731774a6eb7109501c5d9675981c3809682)

2020-08-26 15:31 UTC, dvrg commented on CONTRIBUTING.md
> +```
Iya pak :smile: sy juga jadi bingung awalnya.
Untuk kontennya apa biar lebih bisa spesifik, mungkin harus tau dlu pak yang boleh dikontibusikan secara terbuka bagian yang apa saja ? apakah hanya belajar.md saja, jadi nanti sy tambahkan misal


Syarat menambahkan konten belajar, sertakan judul yang memiliki link ke halaman tujuan, lalu ditambahkan rekomendasi berdasarkan level belajar :
## Referensi Belajar
-  [Judul yang memiliki link](#) - untuk pemula (Opsional)

2020-08-26 16:13 UTC, irvansemestanya commented on CONTRIBUTING.md
> +```
Untuk sekarang nggak ada batasan kok, misalkan, halaman depan bisa sekalian ditambahkan link ke contribution.md ini
...sedangkan untuk.peraturan dan bertanya juga bisa diusulkan lebih baik.

Tapi untuk contoh, memang bisa belajar.md saja

2020-08-27 11:48 UTC, dvrg commented on CONTRIBUTING.md
> +```
baik pak, sy improve dlu isi nya kalau begitu...

2020-09-01 10:50 UTC, andrianowinatra commented on CONTRIBUTING.md
> +## Sertakan Screenshoot (Opsional)
```suggestion
## Sertakan Screenshot (Opsional)
```

2020-09-01 10:51 UTC, andrianowinatra commented on CONTRIBUTING.md
> +Unggah screenshoot ataupun gambar yang berkaitan dengan ide/masalah/pertanyaan yang ingin kamu bahas.
```suggestion
Unggah screenshot ataupun gambar yang berkaitan dengan ide/masalah/pertanyaan yang ingin kamu bahas.
```

2020-09-01 11:28 UTC, irvansemestanya commented
Ada update, @dvrg ?

2020-09-02 01:36 UTC, irvansemestanya commented on CONTRIBUTING.md
> +```
```suggestion
``````markdown
```

2020-09-02 01:39 UTC, irvansemestanya approved these changes

2020-09-02 01:40 UTC, irvansemestanya commented
Menurutku sudah ok sih....

2020-09-02 03:02 UTC, andrianowinatra approved these changes
LGTM

2020-09-02 04:43 UTC, merged